# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PriceView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PriceView

  target 'PriceViewTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FBSnapshotTestCase', '2.1.4', :inhibit_warnings => true
  end

end
